### ISSUE TITLE
Fedora 36: Gtk-WARNING **: cannot open display:

### ISSUE THREAD

**Issue by 0n1cOn3** [ulrichSchreiner/devolo-cockpit#2]
Hi 
I run  ./build as instructed. 
But I'll getting this error when I wanna run Cockpit:

***
~/GitHub/devolo-cockpit on master:  sudo ./cockpit      Error: 126 ✘ at 17:15:21 
 * Starting devolo Network Service devolonetsvc                                        [ OK ] 
No protocol specified

(/opt/devolo/dlancockpit/bin/dlancockpit:7): Gtk-WARNING **: cannot open display: 
***

Thats all what I have :/

**Comment by ulrichSchreiner** [comment]
hi,

i changed the `cockpit` script to mount the `Xauthority` from the correct environment variable. modern linux distro's have this variable and the file is not located in the home folder of the user (it is in `/run/user...` instead).

with my arch the system works.

i don't know fedora very will, so i do not know if it has suport for x11 installed (i think F36 uses wayland).

</usc>

**Comment by 0n1cOn3** [comment]
Hi

Thanks for the feedback! 
I will gonna test the change and let you know if it is working or not. 
I have X11 installed for some older applications which relay on x11 (xorg) but do not work on wayland.

**Comment by 0n1cOn3** [comment]
Hi! 

It's been a while.
And I can say: your edit was a success!

I facing now a different issue and will create new Issue and close this. Cause it's solved 👍🏻
